name = "aave-v3-flashloan"
version = "<%= package.version %>"
description = "Aave's v3 Flashloan Receiver contracts"

[contract.FlashLoanSimpleReceiverBase]
artifact = "FlashLoanSimpleReceiverBase"

[contract.FlashLoanReceiverBase]
artifact = "FlashLoanReceiverBase"

